import { TILE_TYPES } from "./utils.js";

export const GAME_MODES = Object.freeze({
  LITE: "lite",
  ADVANCED: "advanced",
});

export const SPECIAL_RESOURCES = Object.freeze({
  grassland: "fruit",
  jungle: "hardwood",
  arctic: "iron",
  desert: "oil",
});

export const RESOURCE_METADATA = Object.freeze({
  fruit: {
    label: "Fruit",
    purpose: "Population growth",
    terrain: "grassland",
  },
  hardwood: {
    label: "Hardwood",
    purpose: "Buildings",
    terrain: "jungle",
  },
  iron: {
    label: "Iron",
    purpose: "Factories",
    terrain: "arctic",
  },
  oil: {
    label: "Oil",
    purpose: "Advanced units",
    terrain: "desert",
  },
});

export const RESOURCE_BASE_YIELD_PER_TILE = 1;
export const FRUIT_CONSUMPTION_PER_POPULATION = 0.08;
export const FRUIT_SURPLUS_GROWTH_RATE = 0.18;
export const FRUIT_DEFICIT_STABILITY_PENALTY = 3;

export const BUILDING_HARDWOOD_COSTS = Object.freeze({
  [TILE_TYPES.FARM]: 1,
  [TILE_TYPES.FISHERY]: 1,
  [TILE_TYPES.MINE]: 1,
  [TILE_TYPES.MOUNTAIN_MINE]: 2,
  [TILE_TYPES.SCHOOL]: 2,
  [TILE_TYPES.UNIVERSITY]: 3,
  [TILE_TYPES.MILITARY]: 2,
});

export const FACTORY_IRON_COST = 3;
export const FACTORY_HARDWOOD_COST = 2;

export const ADVANCED_UNIT_OIL_COSTS = Object.freeze({
  tanks: 2,
  air: 3,
  naval: 2,
});

// Advanced mode resource upkeep (per turn per building/unit/etc.)
export const ADVANCED_UPKEEP_COSTS = Object.freeze({
  buildings: {
    [TILE_TYPES.FARM]: { hardwood: 0.05 },
    [TILE_TYPES.FISHERY]: { hardwood: 0.05 },
    [TILE_TYPES.MINE]: { hardwood: 0.08, iron: 0.02 },
    [TILE_TYPES.MOUNTAIN_MINE]: { hardwood: 0.1, iron: 0.03 },
    [TILE_TYPES.SCHOOL]: { hardwood: 0.06, iron: 0.04 },
    [TILE_TYPES.UNIVERSITY]: { hardwood: 0.08, iron: 0.06 },
    [TILE_TYPES.MILITARY]: { hardwood: 0.1, iron: 0.08, oil: 0.05 },
    [TILE_TYPES.FACTORY]: { hardwood: 0.15, iron: 0.2, oil: 0.1 },
  },
  units: {
    infantry: { iron: 0.03 },
    tanks: { iron: 0.1, oil: 0.08 },
    air: { iron: 0.08, oil: 0.15 },
    naval: { iron: 0.07, oil: 0.1 },
  },
});

export const BALANCE = {
  actions: {
    defaultActionPoints: 5,
    costs: {
      assignWorkers: 1,
      buildTile: 1,
      destroyTile: 1,
      trainUnit: 1,
      moveOrAttackUnit: 1,
      declareWar: 1,
      trade: 1,
      proposeAlliance: 1,
      breakAlliance: 1,
      embargo: 1,
      researchTech: 1,
      researchBranch: 1,
      endTurn: 0,
    },
  },

  startingProfiles: {
    small: {
      label: "Small Nation",
      territoryTarget: 5,
      population: 24,
      money: 1320,
      resources: { food: 58, materials: 29, education: 18, industry: 0 },
    },
    balanced: {
      label: "Balanced Nation",
      territoryTarget: 7,
      population: 32,
      money: 990,
      resources: { food: 80, materials: 40, education: 25, industry: 0 },
    },
    large: {
      label: "Large Nation",
      territoryTarget: 9,
      population: 42,
      money: 700,
      resources: { food: 102, materials: 51, education: 33, industry: 0 },
    },
  },

  population: {
    capacityPerTile: 10,
    foodConsumptionBase: 0.62,
    foodConsumptionPerEra: 0.06,
    famineFoodPerDeath: 7,
    upkeepMoneyPerPerson: 0.4,
    happiness: {
      default: 65,
      bands: [
        { min: 80, label: "Thriving", workRate: 1.08, stoppageChance: 0, militaryRefusalChance: 0 },
        { min: 65, label: "Content", workRate: 1, stoppageChance: 0, militaryRefusalChance: 0 },
        { min: 45, label: "Uneasy", workRate: 0.9, stoppageChance: 0, militaryRefusalChance: 0 },
        { min: 25, label: "Unhappy", workRate: 0.75, stoppageChance: 0.2, militaryRefusalChance: 0.15 },
        { min: 0, label: "Unrest", workRate: 0.55, stoppageChance: 0.4, militaryRefusalChance: 0.35 },
      ],
      changes: {
        famineDeathPenalty: 3,
        severeFoodDeficitPenalty: 5,
        mildFoodDeficitPenalty: 2,
        unpaidUpkeepPenalty: 3,
        warExhaustionDivisor: 18,
        activeWarPenalty: 2,
        disruptedTradePenalty: 2,
        activeTradeBonus: 1,
        allianceBonus: 1,
        prosperousRecovery: 3,
        peacefulRecovery: 1,
      },
    },
    growth: {
      minimumFoodSurplus: 3,
      thrivingSurplusRatio: 0.8,
      comfortableSurplusRatio: 0.4,
      thrivingGrowth: 2,
      comfortableGrowth: 1,
      marginalGrowth: 0,
      transportMultipliers: [1, 1.1, 1.2, 1.35, 1.5],
      transportHappinessBonus: [0, 1, 1, 2, 2],
    },
  },

  stockpiles: {
    resources: ["food", "materials", "education", "industry"],
    softCaps: {
      food: 180,
      materials: 120,
      education: 95,
      industry: 70,
    },
    minimumMultiplier: 0.45,
  },

  costs: {
    workerAdminPerWorker: 5,
    troopMovement: {
      land: 30,
      water: 60,
    },
    factoryFallbackMoney: 20,
    build: {
      [TILE_TYPES.FARM]: 140,
      [TILE_TYPES.FISHERY]: 170,
      [TILE_TYPES.MINE]: 190,
      [TILE_TYPES.MOUNTAIN_MINE]: 310,
      [TILE_TYPES.SCHOOL]: 230,
      [TILE_TYPES.UNIVERSITY]: 560,
      [TILE_TYPES.MILITARY]: 330,
      [TILE_TYPES.FACTORY]: 780,
    },
    factoryEra4Build: 1250,
    buildEraMultipliers: {
      era3: 1.65,
      era4: 2.35,
    },
    destroy: {
      default: 70,
      [TILE_TYPES.FACTORY]: 160,
    },
  },

  production: {
    eraScalePerEra: 0.2,
    [TILE_TYPES.FARM]: {
      foodBase: 16,
      foodPerTech: 8,
      moneyBase: 28,
      moneyPerTech: 12,
      peopleTechTier: 2,
      people: 1,
      bountifulMultiplier: 2,
    },
    [TILE_TYPES.FISHERY]: {
      foodBase: 12,
      foodPerTech: 6,
      moneyBase: 34,
      moneyPerTech: 10,
      peopleTechTier: 3,
      people: 1,
    },
    [TILE_TYPES.MINE]: {
      materialsBase: 9,
      materialsPerTech: 6,
      moneyBase: 45,
      moneyPerTech: 18,
      peopleTechTier: 3,
      people: 1,
    },
    [TILE_TYPES.MOUNTAIN_MINE]: {
      materialsBase: 15,
      materialsPerTech: 8,
      moneyBase: 58,
      moneyPerTech: 20,
      peopleTechTier: 3,
      people: 1,
    },
    [TILE_TYPES.SCHOOL]: {
      educationBase: 7,
      educationPerTech: 6,
      moneyBase: 32,
      moneyPerTech: 14,
      peopleTechTier: 3,
      people: 1,
    },
    [TILE_TYPES.UNIVERSITY]: {
      educationBase: 14,
      educationPerTech: 8,
      moneyBase: 52,
      moneyPerTech: 18,
      peopleTechTier: 4,
      people: 1,
    },
    [TILE_TYPES.FACTORY]: {
      industryBase: 8,
      industryPerTech: 4,
      moneyBase: 130,
      materialsCostBase: 4,
      educationCostBase: 3,
      educationCostEraDivisor: 2,
      peopleEra: 4,
      people: 1,
    },
    [TILE_TYPES.MILITARY]: {
      moneyBase: 20,
      moneyPerTech: 9,
      materialsTechTier: 2,
      materials: 2,
    },
  },

  war: {
    declarationCost: 220,
    upkeepPerWar: 85,
    upkeepPerUnitStrength: 6,
    unitActiveWarMultiplier: 1,
    deserterShortfallDivisor: 60,
    declarationRelationPenalty: 28,
    globalTrustPenalty: 3,
    formerTradePartnerPenalty: 10,
    formerAlliancePenalty: 8,
    globalFormerTradePartnerPenalty: 5,
    globalFormerAlliancePenalty: 4,
    strategicPowerFloor: 9,
    strategicPowerRatio: 1.35,
    mobilization: {
      peacetimeLevel: 0,
      defaultAtWarLevel: 1,
      fullMobilizationWarThreshold: 2,
      minLevel: 0,
      maxLevel: 2,
      levels: [
        {
          effectivenessMultiplier: 1,
          upkeepMultiplier: 1,
          exhaustionGrowthMultiplier: 1,
        },
        {
          effectivenessMultiplier: 1.12,
          upkeepMultiplier: 1.35,
          exhaustionGrowthMultiplier: 1.35,
        },
        {
          effectivenessMultiplier: 1.25,
          upkeepMultiplier: 1.9,
          exhaustionGrowthMultiplier: 1.8,
        },
      ],
    },
    exhaustion: {
      min: 0,
      max: 100,
      baseGrowthPerTurn: 3,
      perActiveWarGrowth: 1.5,
      peaceRecoveryPerTurn: 5,
      battleLossPerUnit: 1.1,
      winnerLossMultiplier: 0.8,
      loserLossMultiplier: 1.25,
      incomePenaltyThreshold: 30,
      incomeMaxPenalty: 0.35,
      productionPenaltyThreshold: 45,
      productionMaxPenalty: 0.3,
      combatPenaltyThreshold: 70,
      combatMaxPenalty: 0.35,
    },
    combat: {
      attackerTankPower: 5,
      attackerAirPower: 4,
      defenderTankPower: 4,
      defenderAirPower: 3,
      militaryTechPower: 2,
      capitalDefense: 4,
      winnerLossRate: 0.35,
      loserLossRate: 0.8,
    },
    supply: {
      nearbyRadius: 2,
      ownedNearbyBonus: 0.045,
      alliedNearbyBonus: 0.03,
      maxNearbyBonus: 0.18,
      anchorTypes: [TILE_TYPES.MILITARY],
      anchorDistancePenaltyStart: 4,
      penaltyPerAnchorDistance: 0.055,
      maxDistancePenalty: 0.32,
      minimumMultiplier: 0.68,
      maximumMultiplier: 1.18,
    },
    defense: {
      capital: {
        flatBonus: 4,
        multiplierBonus: 0.18,
      },
      developed: {
        types: [
          TILE_TYPES.FARM,
          TILE_TYPES.FISHERY,
          TILE_TYPES.MINE,
          TILE_TYPES.MOUNTAIN_MINE,
          TILE_TYPES.SCHOOL,
          TILE_TYPES.UNIVERSITY,
          TILE_TYPES.FACTORY,
          TILE_TYPES.MILITARY,
        ],
        flatBonus: 1,
        multiplierBonus: 0.04,
      },
      highValue: {
        types: [TILE_TYPES.FACTORY, TILE_TYPES.MILITARY],
        flatBonus: 2,
        multiplierBonus: 0.08,
      },
      terrain: {},
      landform: {},
    },
    siege: {
      progressPerVictory: 1,
      capitalRequiredProgress: 3,
      highValueRequiredProgress: 2,
      highValueTypes: [TILE_TYPES.FACTORY, TILE_TYPES.MILITARY],
    },
  },

  militaryPower: {
    branch: {
      tanks: 10,
      air: 9,
      naval: 8,
    },
    militaryTech: 6,
  },

  unitTypes: {
    infantry: {
      label: "Infantry",
      moveRange: 1,
      attackRange: 1,
      attackMultiplier: 1,
      canEnterWater: false,
      coastalOnly: false,
      ignoresTerrainForMovement: false,
      capturesTerritory: true,
      animation: "infantry",
    },
    tanks: {
      label: "Tanks",
      moveRange: 2,
      attackRange: 1,
      attackMultiplier: 1.35,
      canEnterWater: false,
      coastalOnly: false,
      ignoresTerrainForMovement: false,
      capturesTerritory: true,
      animation: "tank",
    },
    naval: {
      label: "Naval Fleet",
      moveRange: 3,
      attackRange: 2,
      attackMultiplier: 1.2,
      canEnterWater: true,
      coastalOnly: true,
      ignoresTerrainForMovement: false,
      capturesTerritory: true,
      animation: "navy",
    },
    air: {
      label: "Aircraft",
      moveRange: 4,
      attackRange: 4,
      attackMultiplier: 1.5,
      canEnterWater: false,
      coastalOnly: false,
      ignoresTerrainForMovement: true,
      capturesTerritory: false,
      animation: "aircraft",
    },
  },

  trade: {
    alliances: {
      trade: {
        label: "Trade Alliance",
        cost: 120,
        relationBoost: 10,
      },
      military: {
        label: "Military Alliance",
        cost: 180,
        relationBoost: 8,
      },
      research: {
        label: "Research Pact",
        cost: 160,
        relationBoost: 12,
      },
    },
    bundleValues: {
      money: 1,
      food: 1.4,
      materials: 5,
      education: 7,
      industry: 10,
      people: 135,
    },
    pricing: {
      resources: ["food", "materials", "education", "industry"],
      baselinePerPerson: {
        food: 1.8,
        materials: 1.05,
        education: 0.75,
        industry: 0.38,
      },
      scarcityMultiplierMax: 1.85,
      abundanceMultiplierMin: 0.62,
      scarcitySensitivity: 0.7,
      abundanceSensitivity: 0.42,
    },
    routes: {
      baseIncome: 18,
      baseResourceYield: 3,
      creationMinimumValue: 65,
      maxRoutesPerPair: 1,
      relationMinimum: 35,
      relationNeutral: 50,
      relationRangeDivisor: 50,
      relationMultiplierRange: 0.42,
      minimumYieldMultiplier: 0.25,
      minimumResourceScarcityMultiplier: 0.6,
      partnerStrengthDivisor: 1800,
      partnerStrengthMaxBonus: 0.32,
      partnerStrengthWeights: {
        money: 1,
        population: 14,
        territory: 70,
        food: 0.45,
        materials: 1.8,
        education: 2.6,
        industry: 4,
      },
      tradeAllianceIncomeBonus: 0.16,
      tradeAllianceResourceBonus: 1,
      maxIncomePerTurn: 55,
      maxResourceYield: 7,
      disruptionTurns: 3,
      removalRelationCutoff: 12,
      inactiveRemovalGraceTurns: 0,
    },
    dependency: {
      gainPerTrade: 4,
      gainPerActiveTurn: 1,
      decayPerInactiveTurn: 2,
      max: 100,
      rateBonusPerPoint: 0.0025,
      maxRateBonus: 0.18,
      overdependenceThreshold: 58,
      shockMoneyPerPoint: 2.2,
      shockResourcePerPoint: 0.08,
      maxShockMoney: 190,
    },
    embargo: {
      cost: 90,
      durationTurns: 4,
      targetIncomePenalty: 0.45,
      targetResourcePenalty: 0.35,
      relationPenalty: 16,
      globalTrustPenalty: 2,
      retaliationRelationPenalty: 4,
      maxStackedIncomePenalty: 0.7,
    },
    thresholds: {
      economic: 0.88,
      scientific: 0.95,
      balanced: 1,
      aggressive: 1.1,
      default: 1,
    },
    relationFactorDivisor: 420,
    trustBonusPerTrade: 0.025,
    maxTrustBonus: 0.16,
    minimumRequiredFactor: 0.68,
    acceptedRelationGain: 7,
    rejectedRelationPenalty: 4,
    allianceScoreThreshold: 54,
    allianceDurationTurns: 6,
    brokenAgreementPenalty: 12,
    failedAlliancePenalty: 5,
    personalityAllianceBonus: {
      economic: 14,
      scientificResearch: 12,
      aggressiveMilitary: 8,
    },
  },

  tech: {
    categories: {
      farming: { baseCost: 260 },
      mining: { baseCost: 320 },
      education: { baseCost: 360 },
      infrastructure: { baseCost: 390 },
      military: { baseCost: 420 },
    },
    branches: {
      tanks: { baseCost: 900, materialCost: 45 },
      air: { baseCost: 1050, materialCost: 35, educationCost: 35 },
      naval: { baseCost: 1000, materialCost: 50 },
    },
    training: {
      infantryStrengths: [3, 6],
      branchBaseStrength: {
        tanks: 8,
        air: 7,
        naval: 7,
      },
      era3Scale: 1.2,
      era4Scale: 1.45,
      moneyPerStrength: 35,
      peopleDivisor: 3,
      materialsPerStrength: {
        early: 0.55,
        era4: 0.85,
      },
      branchMoneyMultiplier: {
        tanks: 1.85,
        air: 1.75,
        naval: 1.7,
        infantry: 1,
      },
      branchMaterialsMultiplier: {
        default: 2.15,
        air: 1.4,
      },
      industryBase: 10,
      industryPerStrength: 1.6,
      industryPerBranchLevel: 0.18,
      airEducationBase: 8,
      airEducationPerStrength: 1.25,
    },
    factoryRequirements: {
      activeMinesBase: 3,
      activeSchoolsBase: 2,
      activePerFactory: 2,
      populationBase: 35,
      populationPerFactory: 8,
      miningTier: 2,
      educationTier: 2,
    },
    research: {
      costExponent: 1.85,
      maxTier: 4,
      activeTilesPerTier: 2,
      resourceCostRate: 0.08,
      resourceCostExponent: 1.5,
    },
    branchResearch: {
      moneyExponent: 1.9,
      materialsExponent: 1.45,
      educationExponent: 1.35,
      industryBase: 25,
      industryExponent: 1.35,
      fallbackEducationCost: 20,
      requiredMilitaryTier: 3,
      maxLevel: 3,
    },
  },

  score: {
    resourceValues: {
      food: 0.5,
      materials: 2,
      education: 3,
      industry: 5,
    },
    buildingValue: {
      default: 75,
      [TILE_TYPES.FACTORY]: 180,
      [TILE_TYPES.UNIVERSITY]: 150,
    },
    techTierValue: 220,
    branchTierValue: 260,
    populationValue: 18,
    territoryValue: 90,
    militaryValue: 22,
  },
};
